resource_group_name           = "nestjs-cicd-prod-rg"
azure_location                = "northeurope"
web_app_service_plan_name     = "nestjs_cicd_app_plan"
web_app_service_name          = "nestjs_cicd_app"
web_app_service_slot_name     = "nestjs_cicd_app_slot"
web_app_service_node_version  = "20-lts"
web_app_service_logs_level    = "Warning"