resource_group_name    = "nestjs-cicd-prod-rg"
# azure_location = "westus2"
azure_location         = "North Europe"
blue_app_name          = "blue-nestjs-cicd-app"
green_app_name         = "green-nestjs-cicd-app"
active_app_environment = "blue"
traffic_manager_name   = "nestjs-cicd-traffic-manager"